import type { Profile, Match, Like, Conversation, Message } from './types';

export const mockProfiles: Profile[] = [
  {
    id: 'user2',
    email: 'sarah@example.com',
    first_name: 'Sarah',
    age: 24,
    bio: 'Passionnée par le yoga et les voyages. J\'aime découvrir de nouveaux endroits et rencontrer des gens intéressants.',
    city: 'Paris',
    city_lat: 48.8566,
    city_lng: 2.3522,
    photos: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop'],
    skills: [{ name: 'Design', level: 8 }, { name: 'Photography', level: 7 }],
    interests: ['Voyage', 'Yoga', 'Photographie'],
    preferences: null,
    plan: 'free',
    stripe_customer_id: null,
    stripe_subscription_id: null,
    subscription_status: null,
    subscription_plan: 'free',
    swipes_today: 0,
    messages_today: 0,
    likes_today: 0,
    last_swipe_date: null,
    last_message_date: null,
    last_like_date: null,
    is_onboarded: true,
    is_suspended: false,
    suspension_reason: null,
    email_confirmed: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user3',
    email: 'emma@example.com',
    first_name: 'Emma',
    age: 26,
    bio: 'Développeuse web qui aime coder et sortir en nature. Toujours prête pour une randonnée!',
    city: 'Lyon',
    city_lat: 45.7640,
    city_lng: 4.8357,
    photos: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop'],
    skills: [{ name: 'Development', level: 9 }, { name: 'Design', level: 6 }],
    interests: ['Coding', 'Nature', 'Musique'],
    preferences: null,
    plan: 'business',
    subscription_plan: 'business',
    stripe_customer_id: null,
    stripe_subscription_id: null,
    subscription_status: null,
    subscription_plan: 'business',
    swipes_today: 0,
    messages_today: 0,
    likes_today: 0,
    last_swipe_date: null,
    last_message_date: null,
    last_like_date: null,
    is_onboarded: true,
    is_suspended: false,
    suspension_reason: null,
    email_confirmed: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user4',
    email: 'julie@example.com',
    first_name: 'Julie',
    age: 22,
    bio: 'Étudiante en marketing, j\'aime les sorties entre amis et les bons restaurants.',
    city: 'Bordeaux',
    city_lat: 44.8378,
    city_lng: -0.5792,
    photos: ['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=500&fit=crop'],
    skills: [{ name: 'Marketing', level: 7 }, { name: 'Social Media', level: 8 }],
    interests: ['Marketing', 'Gastronomie', 'Mode'],
    preferences: null,
    plan: 'free',
    stripe_customer_id: null,
    stripe_subscription_id: null,
    subscription_status: null,
    subscription_plan: 'free',
    swipes_today: 0,
    messages_today: 0,
    likes_today: 0,
    last_swipe_date: null,
    last_message_date: null,
    last_like_date: null,
    is_onboarded: true,
    is_suspended: false,
    suspension_reason: null,
    email_confirmed: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user5',
    email: 'lea@example.com',
    first_name: 'Léa',
    age: 25,
    bio: 'Graphiste créative avec passion pour l\'art et le design. Toujours à la recherche d\'inspiration!',
    city: 'Marseille',
    city_lat: 43.2965,
    city_lng: 5.3698,
    photos: ['https://images.unsplash.com/photo-1502185881662-2d440ac1c159?w=400&h=500&fit=crop'],
    skills: [{ name: 'Design', level: 9 }, { name: 'Illustration', level: 8 }],
    interests: ['Art', 'Design', 'Musique'],
    preferences: null,
    plan: 'business_pro',
    subscription_plan: 'business_pro',
    stripe_customer_id: null,
    stripe_subscription_id: null,
    subscription_status: null,
    swipes_today: 0,
    messages_today: 0,
    likes_today: 0,
    last_swipe_date: null,
    last_message_date: null,
    last_like_date: null,
    is_onboarded: true,
    is_suspended: false,
    suspension_reason: null,
    email_confirmed: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockMatches: Match[] = [
  {
    id: 'match1',
    user1_id: 'current_user',
    user2_id: 'user2',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    is_viewed: false,
  },
  {
    id: 'match2',
    user1_id: 'current_user',
    user2_id: 'user3',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    is_viewed: true,
  },
];

export const mockLikes: Like[] = [
  {
    id: 'like1',
    liker_id: 'user4',
    liked_id: 'current_user',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    is_viewed: false,
  },
  {
    id: 'like2',
    liker_id: 'user5',
    liked_id: 'current_user',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    is_viewed: false,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv1',
    user1_id: 'current_user',
    user2_id: 'user2',
    match_id: 'match1',
    last_message: 'Salut! Ça va?',
    last_message_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'conv2',
    user1_id: 'current_user',
    user2_id: 'user3',
    match_id: 'match2',
    last_message: 'On se voit ce weekend?',
    last_message_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg1',
    conversation_id: 'conv1',
    sender_id: 'user2',
    content: 'Salut! Comment ça va?',
    message_type: 'text',
    file_url: null,
    file_name: null,
    file_size: null,
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    conversation_type: 'match',
  },
  {
    id: 'msg2',
    conversation_id: 'conv1',
    sender_id: 'current_user',
    content: 'Très bien! Et toi?',
    message_type: 'text',
    file_url: null,
    file_name: null,
    file_size: null,
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    conversation_type: 'match',
  },
  {
    id: 'msg3',
    conversation_id: 'conv1',
    sender_id: 'user2',
    content: 'Super! Je suis content de te parler',
    message_type: 'text',
    file_url: null,
    file_name: null,
    file_size: null,
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    conversation_type: 'match',
  },
];

export const mockCurrentUser: Profile = {
  id: 'current_user',
  email: 'alex@example.com',
  first_name: 'Alex',
  age: 27,
  bio: 'Entrepreneur passionné par la tech et les rencontres intéressantes.',
  city: 'Paris',
  city_lat: 48.8566,
  city_lng: 2.3522,
  photos: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop'],
  skills: [{ name: 'Development', level: 8 }, { name: 'Leadership', level: 7 }],
  interests: ['Tech', 'Startup', 'Voyage'],
  preferences: null,
  plan: 'business',
    subscription_plan: 'business',
  stripe_customer_id: null,
  stripe_subscription_id: null,
  subscription_status: null,
  swipes_today: 0,
  messages_today: 0,
  likes_today: 0,
  last_swipe_date: null,
  last_message_date: null,
  last_like_date: null,
  is_onboarded: true,
  is_suspended: false,
  suspension_reason: null,
  email_confirmed: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};
